[package]
name = "ccwc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
clap = {version = "4", features = ["derive"] }


[profile.release]
strip = true
lto = true
